# Назва конфігурації автоматичної збірки ядра Archi
name: Build Archi

# Тригери запуску конфігурації
on:
  push:
    branches: [ "master", "main" ] # Автозапуск при коміті у головну гілку
  workflow_dispatch: # Дозвіл ручного запуску через інтерфейс GitHub

jobs:
  build:
    runs-on: ubuntu-latest # Використовуємо Linux-середовище

    steps:
      # Крок 1: Клонуємо форк головного репозиторію Archi
      - name: Checkout Repository
        uses: actions/checkout@v5

      # Крок 2: Встановлюємо Java 21 (жорстка вимога свіжого Eclipse Tycho)
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Крок 3: Компіляція та пакування з пропуском тестів
      # Фаза verify гарантує, що Tycho створить фінальні інсталятори застосунку
      - name: Build Archi with Maven
        run: mvn clean verify -B -e -DskipTests=true

      # Крок 4: Завантажуємо готові бінарники (Windows, Linux, macOS)
      # Оскільки фаза verify пройдена успішно, файли гарантовано будуть у цій папці
      - name: Upload Archi Binaries
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: Archi-Binaries
          path: com.archimatetool.editor.product/target/products/
